### PR TITLE
Team Authorization via oAuth

### PR DESCRIPTION
**Pull request by knowtheory**
This is a branch that sets up a lambda function which can accept authorization requests from Slack, and record authorization details for later use.

### CODE REVIEW

**Comment by chriszarate** [comment]
hold me closer oauth dancer

**Comment by knowtheory** [comment]
Quick rundown:

* Sequelize is an ORM.  It uses bluebird promises.
* we're using the postgres backend for Sequelize.
* Sequelize has some CLI helpers and a default project layout (which we're defying a little)
* There's a `lib/migrations` and `lib/models` directory which contain what you think
* We have two models, `Authorization` and `Team`
* The index function is pretty minimalist, it was just a huge pain the ass to debug.
* The index function receives a `code` from an attempted Slack authorization via the API Gateway`
* The index function then makes a `Request` to slack to verify the authorization
* Slack returns back an authorization object which contains the tokens we want.
* We look up or create a record the team in question
* We then store the authorization (and there could be more than one authorization per team)
* And then we tell them they successfully added the bot.

IMPORTANT NOTE:
* Sequelize is a pain in the ass and requires us to close down the DB connection explicitly so that the Lambda function can exit gracefully (necessary so that the API Gateway knows what's up).

**Comment by chriszarate** [comment]
yayyyy awesome :+1:

**Comment by knowtheory** [comment]
Oh by the way, we're pinned to the 6.4.2 (rather than 7.x) of the `pg` package because of this issue: https://github.com/sequelize/sequelize/issues/8043

**Pull request merged**
